import React, { useState } from 'react';
import { CAMPUS_REPORTS } from '../../data/campusData';

export const CampusReportsView: React.FC = () => {
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const triggerToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  return (
    <div className="space-y-6 pb-12 animate-fade-in select-none">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-white">Campus Reports</h2>
        <p className="text-sm text-[#94A3B8] mt-0.5">
          Generate actionable intelligence from campus data.
        </p>
      </div>

      {toastMessage && (
        <div className="p-3 rounded-xl bg-[#10B981]/20 border border-[#10B981]/40 text-xs text-[#10B981] flex items-center gap-2 animate-fade-in">
          <span className="material-symbols-outlined text-sm">check_circle</span>
          <span>{toastMessage}</span>
        </div>
      )}

      {/* AI EXECUTIVE SUMMARY */}
      <div className="card-depth p-5 border-l-4 border-l-[#8B5CF6]">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-[#8B5CF6] text-base">✦</span>
          <h3 className="text-sm font-bold text-white uppercase tracking-wider">
            AI EXECUTIVE SUMMARY
          </h3>
          <span className="text-[10px] px-2 py-0.5 rounded-full bg-[#10B981]/20 text-[#10B981] font-semibold">
            Institutional Health: Stable
          </span>
        </div>
        <p className="text-xs text-[#E2E8F0] leading-relaxed">
          "Overall campus performance is stable. Placement readiness increased 5.8% across technical departments, while ECE and ME show the largest skill gaps in Cloud Computing and ML. Attendance risk has increased among second-year cohorts, with 126 students below minimum threshold. Lab utilization across AI Studio and Cloud Lab averages 85% peak draw."
        </p>
        <div className="flex items-center gap-4 mt-3 text-[11px] text-[#94A3B8]">
          <span>Generated by Databricks Genie</span>
          <span>•</span>
          <span>Compiled: Sep 02, 2026</span>
        </div>
      </div>

      {/* 6 REPORT CARDS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {CAMPUS_REPORTS.map((report) => (
          <div key={report.id} className="card-depth p-5 flex flex-col justify-between space-y-4">
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] uppercase font-bold text-[#818CF8] tracking-wider">
                  {report.category}
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-[#10B981]/15 text-[#10B981] font-medium">
                  {report.status}
                </span>
              </div>

              <h4 className="text-sm font-bold text-white mb-1.5">{report.title}</h4>
              <p className="text-[11px] text-[#94A3B8] leading-normal">{report.summary}</p>

              <div className="mt-4 p-3 rounded-xl bg-[#111728] border border-[#1E293D] flex items-center justify-between">
                <span className="text-[10px] text-[#64748B]">{report.metricLabel}</span>
                <span className="text-sm font-bold text-white">{report.keyMetric}</span>
              </div>
            </div>

            <div className="pt-3 border-t border-[#1E293B] flex items-center justify-between gap-2">
              <button
                onClick={() => triggerToast(`Preview opened for ${report.title}`)}
                className="flex-1 py-1.5 px-2.5 rounded-lg bg-[#111728] border border-[#232F46] text-white text-[11px] font-medium hover:border-[#4F46E5] transition-colors"
              >
                Preview
              </button>
              <button
                onClick={() => triggerToast(`Exporting ${report.title} as PDF...`)}
                className="flex-1 py-1.5 px-2.5 rounded-lg bg-[#111728] border border-[#232F46] text-[#818CF8] text-[11px] font-medium hover:border-[#4F46E5] transition-colors"
              >
                Export PDF
              </button>
              <button
                onClick={() => triggerToast(`Re-generating latest data for ${report.title}...`)}
                className="p-1.5 rounded-lg bg-[#4F46E5] text-white hover:bg-[#4338CA] transition-colors"
                title="Generate Latest"
              >
                <span className="material-symbols-outlined text-[16px]">refresh</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
